[tasks.generate_frames]
command = "ffmpeg"
args = [
# "You like jazz?"
    #"-ss",
    #"1393",
    "-t",
    "120",
    "-probesize",
    "100M",
    "-analyzeduration",
    "100M",
    "-an",
    "-sn",
    "-y",
    "-i",
    "resources/raw/video.mkv",
    "-r",
    "4",
    "-pix_fmt",
    "rgb24",
    "-vf",
    "scale=320:240:force_original_aspect_ratio=decrease,pad=320:240:(ow-iw)/2:(oh-ih)/2,setsar=1",
    #"crop=iw-400,scale=320:240",
    "resources/video/video%d.png",
]

[tasks.package_frames]
command = "cargo"
args = [
    "run",
    "--manifest-path",
    "frame-encoder/Cargo.toml",
    "--",
    "./resources/video",
    "482",
    "./resources/video.bin",
]
dependencies = [
    "generate_frames",
]

[tasks.video]
dependencies = [
    "package_frames",
]

[tasks.clean]
command = "rm"
args = [
    "-rf",
    "resources/video/*",
    "resources/video.bin",
]
