[tasks.ticevid]
command = "fasmg"
args = ["src/main.asm", "bin/ticevid.8xp"]

[tasks.encode_video]
command = "ffmpeg"
args = [
# "You like jazz?"
  "-ss",
  "1393",
  "-t",
  "5",
  "-probesize",
  "100M",
  "-analyzeduration",
  "100M",
  "-an",
  "-sn",
  "-y",
  "-i",
  "resources/raw/video.mkv",
  "-r",
  "3",
  "-pix_fmt",
  "rgb24",
  "-vf",
  "crop=iw-400,scale=320:240",
  "resources/video/video%d.png",
]

[tasks.clean]
command = "rm"
args = [
  "-f",
  "bin/*",
  "resources/video/*",
]
