#pragma once

typedef enum {
    TICEVID_SUCCESS = 0,
    TICEVID_USER_EXIT,
    TICEVID_USB_INIT_ERROR,
    TICEVID_USB_ENABLE_ERROR,
    TICEVID_MSD_OPEN_ERROR,
    TICEVID_MSD_READ_ERROR,
    TICEVID_VIDEO_HEADER_MEMORY,
    TICEVID_VIDEO_CHUNK_MEMORY,
    TICEVID_VIDEO_HEADER_INVALID,
    TICEVID_FONT_MISSING,
    TICEVID_FONT_INVALID,
} ticevid_result_t;
