#pragma once

typedef enum [[nodiscard]] {
    TICEVID_SUCCESS = 0,
    TICEVID_USER_EXIT,
    TICEVID_USB_INIT_ERROR,
    TICEVID_USB_ENABLE_ERROR,
    TICEVID_MSD_OPEN_ERROR,
    TICEVID_MSD_READ_ERROR,
    TICEVID_VIDEO_HEADER_MEMORY,
    TICEVID_VIDEO_CHUNK_MEMORY,
    TICEVID_VIDEO_CONTAINER_INVALID,
    TICEVID_VIDEO_CONTAINER_NULL,
    TICEVID_VIDEO_CONTAINER_VERSION,
    TICEVID_VIDEO_CONTAINER_TITLE,
    TICEVID_FONT_MISSING,
    TICEVID_FONT_INVALID,
} ticevid_result_t;

// Continues if success, else returns.
#define EARLY_EXIT(a) ({ ticevid_result_t result = a; if (result != TICEVID_SUCCESS) { return result; } })
